name: Dependency Review (Fail on moderate+)

on:
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Run dependency review
        uses: actions/dependency-review-action@2031cfc080254a8a887f58cffee85186f0e49e48
        with:
          fail-on-severity: moderate
          repo-token: ${{ secrets.GITHUB_TOKEN }}
